package:
  name: pymiesim
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../
  git_url: https://github.com/MartinPdeS/PyMieSim.git

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - scikit-build-core ~=0.3
    - pybind11 ~=2.13
    - python-build ~=1.2
    - setuptools_scm[toml] ~=8.0
  run:
    - martinpdes::pyoptik
    - numpy ~=1.26
    - pydantic ~=2.9.2
    - pint-pandas ~=0.6
    - tabulate ~=0.9

about:
  home: https://github.com/MartinPdeS/PyMieSim
  license: MIT
  summary: "A package for light scattering computation."
  description: PyMieSim is a library for light scattering simulation using the Mie theory.
  dev_url: https://github.com/MartinPdeS/PyMieSim
  doc_url: https://pymiesim.readthedocs.io
  license_file: LICENSE
  platforms:
    - linux-64
    - osx-64
    - win-64
  keywords:
    - optics
    - scattering
    - mie theory
    - light
    - physics
    - computational optics
    - simulation

test:
  imports:
    - PyMieSim
  requires:
    - pytest>=0.6
    - pytest-cov>=2.0
    - pytest-json-report==1.5.0
    - mypy>=0.910
    - flake8>=3.9
    - tox>=3.24
    - coverage==7.6.1
  commands:
    - pytest --ignore=tests/gui
  source_files:
    - tests

doc:
  requires:
    - numpydoc==1.8.0
    - sphinx>=5.1.1
    - sphinx-gallery==0.17.1
    - sphinx-rtd-theme==2.0.0
    - pydata-sphinx-theme==0.15.4
  commands:
    - sphinx-build -b html docs/source docs/build


extra:
  recipe-maintainers:
    - MartinPdeS