# {% set git_tag = GIT_DESCRIBE_TAG if GIT_DESCRIBE_TAG else "0.1.0" %}
# {% set version = load_setup_py_data().get('version') %}

package:
  name: pymiesim
  # version: "{{ version }}"
  version: "{{ GIT_DESCRIBE_TAG }}"
  # version: "{{ git_tag.replace('v', '') }}"
  # version: "{{ GIT_DESCRIBE_TAG.replace('v', '') }}"

source:
  git_url: https://github.com/MartinPdeS/PyMieSim.git

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - python {{ PY_VER }}*
    - scikit-build-core ~=0.3
    - pybind11 ~=2.13
    - python-build ~=1.2
    - setuptools_scm[toml] ~=8.0
  run:
    - python {{PY_VER}}*
    - martinpdes::pyoptik
    - numpy ~=1.26
    - pydantic ~=2.9.2
    - pint-pandas ~=0.6
    - tabulate ~=0.9

about:
  home: https://github.com/MartinPdeS/PyMieSim
  license: MIT
  summary: "A package for light scattering computation."
  description: PyMieSim is a library for light scattering simulation using the Mie theory.
  dev_url: https://github.com/MartinPdeS/PyMieSim
  doc_url: https://pymiesim.readthedocs.io
  license_file: LICENSE
  keywords:
    - optics
    - scattering
    - mie theory
    - light
    - physics
    - computational optics
    - simulation

files:
  include:
    - "PyMieSim/binary/*.so"

test:
  imports:
    - PyMieSim
  requires:
    - python {{PY_VER}}*
    - pytest>=0.6
    - pytest-cov>=2.0
    - pytest-json-report==1.5.0
    - coverage==7.6.1
  commands:
    - pytest --ignore=tests/gui
  source_files:
    - tests

extra:
  recipe-maintainers:
    - MartinPdeS