package:
  name: pymiesim
  version: "{{ load_setup_py_data().get('version') }}"

source:
  path: .

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3.10
    - pip
    - scikit-build-core >=0.3.3   # Add scikit-build-core to host requirements
    - pybind11                    # Add pybind11 to host requirements if used during build
    - setuptools_scm[toml] >=8.0  # Add setuptools_scm for versioning
  run:
    - python >=3.10

about:
  home: https://github.com/MartinPdeS/PyMieSim
  license: MIT
  summary: "A package for light scattering computation."
