package:
  name: pymiesim
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: .

build:
  number: 0
  script: |
    {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
    # export PIP_NO_BUILD_ISOLATION=True
    # export PIP_NO_INDEX=False
    # export PIP_NO_DEPENDENCIES=False

requirements:
  host:
    - python>=3.10
    - scikit-build-core>=0.3.3
    - pybind11
    - build
    - setuptools_scm[toml]>=8.0
  run:
    - numpy>=1.26.0
    - pydantic==2.9.2
    - pint-pandas
    - PyOptik
    - tabulate==0.9.0

about:
  home: https://github.com/MartinPdeS/PyMieSim
  license: MIT
  summary: "A package for light scattering computation."
  description: PyMieSim is a library for light scattering simulation using the Mie theory.
  dev_url: https://github.com/MartinPdeS/PyMieSim
  doc_url: https://pymiesim.readthedocs.io
  license_file: LICENSE
  platforms:
    - linux-64
    - osx-64
    - win-64
  keywords:
    - optics
    - scattering
    - mie theory
    - light
    - physics
    - computational optics
    - simulation
    - numpy

test:
  imports:
    - PyMieSim
  requires:
    - pymiescatt
    - scipy==1.11.3
    - pytest>=0.6
    - pytest-cov>=2.0
    - pytest-json-report==1.5.0
    - mypy>=0.910
    - flake8>=3.9
    - tox>=3.24
    - coverage==7.6.1
  source_files:
    - tests
  commands:
    - pytest --ignore=tests/gui --ignore=tests/validation

doc:
  requires:
    - pymiescatt
    - scipy==1.11.3
    - numpydoc==1.8.0
    - sphinx>=5.1.1
    - sphinx-gallery==0.17.1
    - sphinx-rtd-theme==2.0.0
    - pydata-sphinx-theme==0.15.4
  commands:
    - sphinx-build -b html docs/source docs/build


extra:
  recipe-maintainers:
    - MartinPdeS