package:
  name: pymiesim
  version: "{{ load_setup_py_data().get('version') }}"

source:
  path: .

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"  # Uses scikit-build's build system

requirements:
  host:
    - python >=3.10                 # Python version requirement
    - pip                           # Ensure pip is available
    - scikit-build-core >=0.3.3     # Required for scikit-build to work properly
    - cmake >=3.19                  # scikit-build requires cmake to build C/C++ extensions
    - ninja                         # A lightweight build system often used by scikit-build
    - pybind11                      # If you are using pybind11 to create Python bindings for C++ code
    - setuptools_scm[toml] >=8.0    # Version management


  run:
    - python >=3.10

about:
  home: https://github.com/MartinPdeS/PyMieSim
  license: MIT
  summary: "A package for light scattering computation."
