package:
  name: pymiesim
  version: "{{ load_setup_py_data().get('version') }}"

source:
  path: .

build:
  noarch: python
  script: |
    {{ PYTHON }} -m pip install build --no-deps --ignore-installed -vvv  # Install the build tool from PyPI
    {{ PYTHON }} -m build . --no-isolation -v                            # Use build to build the package
    {{ PYTHON }} -m pip install dist/*.whl --no-deps --ignore-installed  # Install the built wheel

requirements:
  host:
    - python >=3.10
    - pip
    - scikit-build-core >=0.3.3  # Required for scikit-build-core during build
    - pybind11                   # Required for pybind11 during build
    - setuptools_scm[toml] >=8.0 # Required for setuptools_scm during build

  run:
    - python >=3.10

about:
  home: https://github.com/MartinPdeS/PyMieSim
  license: MIT
  summary: "A package for light scattering computation."
