package:
  name: pymiesim
  version: "{{ load_setup_py_data().get('version') }}"

source:
  path: .

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m build . --no-isolation"

requirements:
  host:
    - python >=3.10
    - pip
    - scikit-build-core >=0.3.3
    - pybind11
    - setuptools_scm[toml] >=8.0
    - build

  run:
    - python >=3.10

about:
  home: https://github.com/MartinPdeS/PyMieSim
  license: MIT
  summary: "A package for light scattering computation."
  description: PyMieSim is a library for light scattering simulation using the Mie theory.
  dev_url: https://github.com/MartinPdeS/PyMieSim
  doc_url: https://pymiesim.readthedocs.io
  license_file: LICENSE
  platforms:
    - linux-64
    - osx-64
    - win-64
  keywords:
    - optics
    - scattering
    - mie theory
    - light
    - physics
    - computational optics
    - simulation
    - numpy

extra:
  recipe-maintainers:
    - MartinPdeS