name: Deploy Conda Package

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_publish_conda_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'

      - name: Create Conda Environment and Install Dependencies
        run: |
          conda install conda-build anaconda-client -y
          conda config --set anaconda_upload yes
          cmake -DCMAKE_INSTALL_PREFIX=$PREFIX .
          cmake --build . --target install -- VERBOSE=1
          # conda build .

      - name: Upload to Anaconda (if tag)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          anaconda upload /path/to/package.tar.bz2
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}  # Ensure the Anaconda token is set

