name: Pages Deploy After Version Update

on:
  workflow_run:
    workflows: ["Update Version Switcher"]
    types:
      - completed

jobs:
  deploy_pages:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout documentation_page branch
        uses: actions/checkout@v4
        with:
          ref: documentation_page

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
